Kernel360/KDEV5-Roadeye-BE

roadeye-api/roadeye-api-hq/build.gradle
roadeye-api/roadeye-api-hq/src/main/resources/application.yml
roadeye-api/roadeye-api-mdt-log-collector/build.gradle
roadeye-monitoring/build.gradle
roadeye-monitoring/docker-compose.local.yml
roadeye-monitoring/docker/collector/otel-collector.yml
roadeye-monitoring/docker/grafana/grafana-datasources.yml
roadeye-monitoring/docker/prometheus/prometheus.yml
roadeye-monitoring/docker/tempo/tempo.yml
roadeye-monitoring/src/main/resources/monitoring.yml
roadeye-plugin/build.gradle.kts
roadeye-plugin/src/main/kotlin/roadeye-jib.gradle.kts
settings.gradle

---
- resolves #8 
- opentelemetry + tempo + loki + promethus + grafana를 통한 모니터링 환경 구성

feat: 로컬 모니터링 도구 추가

---

roadeye-domain/roadeye-domain-hq/build.gradle
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/domain/common/BaseEntity.java
settings.gradle

feat: hq 도메인 모듈

---

roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/domain/common/BaseEntity.java

refactor: active -> deleted 변경

---

roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/domain/common/BaseEntity.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/domain/common/EntityLifecycleStatus.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/employee/service/EmployeeService.java
roadeye-domain/roadeye-domain-hq/src/test/java/org/re/hq/employee/service/EmployeeServiceTest.java

---
- resolves #36 
BaseEntiy에서 삭제 여부를 boolean에서 enum으로 변경했습니다.

feat: 직원 활성화, 비활성화, 삭제에 대한 도메인 서비스 기능 추가

---

roadeye-api/roadeye-api-mdt-log-collector/src/main/java/org/re/mdtlog/collector/app/cyclelog/dto/MdtAddCycleLogRequest.java
roadeye-api/roadeye-api-mdt-log-collector/src/main/java/org/re/mdtlog/collector/app/ignition/dto/MdtIgnitionOffRequest.java
roadeye-api/roadeye-api-mdt-log-collector/src/main/java/org/re/mdtlog/collector/app/ignition/dto/MdtIgnitionOnRequest.java
roadeye-domain/roadeye-domain-mdt-log/src/main/java/org/re/mdtlog/domain/MdtLogEventType.java
roadeye-domain/roadeye-domain-mdt-log/src/main/java/org/re/mdtlog/domain/MdtLogGpsCondition.java
roadeye-domain/roadeye-domain-mdt-log/src/test/java/org/re/mdtlog/domain/MdtLogRepositoryTest.java
roadeye-domain/roadeye-domain-mdt-log/src/test/resources/application.yml

refactor: enum의 원소를 대문자 표기로 변경 + 테스트 케이스 수정

---

roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/domain/common/BaseEntity.java

refactor:  BaseEntity class -> abstract class 변경

---

roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/config/TenantConfig.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/config/WebSecurityConfig.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/security/userdetails/CompanyUserDetails.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/security/userdetails/CompanyUserDetailsService.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/tenant/TenantIdProvider.java
roadeye-api/roadeye-api-hq/src/test/java/org/re/hq/admin/controller/CompanyLoginTest.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/employee/domain/Employee.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/employee/domain/EmployeeRepository.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/employee/service/EmployeeService.java
roadeye-domain/roadeye-domain-hq/src/test/java/org/re/hq/employee/service/EmployeeServiceTest.java

---
- resolves #28 
`@Where` 애노테이션이 deprecated 되어 `@SQLRestriction`로 변경

feat: 직원 정보 조회 기능 구현

---

roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/reservation/domain/CarReservation.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/reservation/service/CarReservationService.java
roadeye-domain/roadeye-domain-hq/src/test/java/org/re/hq/reservation/service/CarReservationServiceTest.java

---
- resolves #29 
예약 승인, 반려 기능 작성

feat: 예약 승인, 반려 기능

---

roadeye-api/roadeye-api-hq/build.gradle
roadeye-api/roadeye-api-hq/src/main/resources/application.yml
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/Car.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/CarIgnitionStatus.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/CarLocation.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/CarMileage.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/CarProfile.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/domain/CarStatus.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/repository/CarRepository.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/car/service/CarService.java
roadeye-domain/roadeye-domain-hq/src/test/java/org/re/hq/car/service/CarServiceTest.java

#22 차량등록기능
---
- resolves #
엔티티 분리하긴했는데 다르게 분리하면 좋겠다 싶으시면 의견주세요

[Feature] 차량 등록 기능

---

roadeye-api/roadeye-api-hq/build.gradle

---
- resolves #
- 직접 커밋 못해서 이런 변경도 PR 만들어야함

feat: Mysql 드라이버 추가

---

roadeye-api/roadeye-api-hq/src/main/java/org/re/hq/employee/api/payload/EmployeeSearchResponse.java
roadeye-domain/roadeye-domain-hq/src/main/java/org/re/hq/company/domain/CompanyQuoteStatus.java

fix: 오타 수정

---

.github/workflows/deploy-dev-docker.yml
roadeye-plugin/src/main/kotlin/roadeye-jib.gradle.kts

---
- resolves #9 
> jib가 포함된 Docker Image를 빌드하고, AWS ECR 및 OCI OCR에 선택적으로 배포 가능할 수 있는 파이프라인 작성

CI/CD 업데이트

---

roadeye-api/roadeye-api-hq/src/main/java/org/re/config/WebSecurityConfig.java

fix: disable cors

---

roadeye-api/roadeye-api-hq/src/main/java/org/re/config/WebSecurityConfig.java

fix: fix cors

---

roadeye-api/roadeye-api-hq/src/main/java/org/re/car/api/CarApi.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/car/service/CarService.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/driving/api/DrivingHistoryApi.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/driving/api/payload/DrivingHistoryInfo.java
roadeye-api/roadeye-api-hq/src/main/java/org/re/driving/service/DrivingHistoryService.java
roadeye-domain/roadeye-domain-core/src/main/java/org/re/driving/repository/DrivingHistoryCustomRepository.java
roadeye-domain/roadeye-domain-core/src/main/java/org/re/driving/repository/DrivingHistoryRepository.java
roadeye-domain/roadeye-domain-core/src/main/java/org/re/driving/repository/impl/DrivingHistoryCustomRepositoryImpl.java
roadeye-domain/roadeye-domain-core/src/main/java/org/re/driving/service/DrivingHistoryDomainService.java

feat: 주행기록 조회 api 추가

---

roadeye-consumer/build.gradle

healthcheck 용도임
---
- resolves #

feat: consumer에 web 추가해서 actuator 노출

---

roadeye-api/roadeye-api-hub/src/main/java/org/re/mdtlog/service/MdtIgnitionService.java

feat: ignition off typo

---

hub/src/main/java/org/re/config/WebMvcConfig.java

fix: hub module cors

---

application/src/main/java/org/re/employee/api/EmployeeApi.java
application/src/main/java/org/re/employee/api/payload/AccountStatus.java
application/src/main/java/org/re/employee/api/payload/EmployeeInfo.java
application/src/main/java/org/re/employee/api/payload/EmployeeStatusChangeRequest.java
application/src/main/java/org/re/employee/service/EmployeeService.java
application/src/test/java/org/re/admin/api/CompanyLoginTest.java
application/src/test/java/org/re/employee/service/EmployeeServiceTest.java
core/src/main/java/org/re/company/service/CompanyDomainService.java
core/src/main/java/org/re/employee/domain/Employee.java
core/src/main/java/org/re/employee/dto/UpdateEmployeeCommand.java
core/src/main/java/org/re/employee/service/EmployeeDomainService.java
core/src/test/java/org/re/company/service/CompanyDomainServiceTest.java
core/src/test/java/org/re/employee/service/EmployeeDomainServiceTest.java

---
- resolves #
-  "feat:" 기능 추가
-  "refactor": 코드 정리 (기능 변경 X)

feat: API 수정 및 리팩토링

---

application/src/main/java/org/re/employee/api/EmployeeApi.java
application/src/main/java/org/re/employee/api/payload/EmployeeStatusCount.java
application/src/main/java/org/re/employee/service/EmployeeService.java
core/src/main/java/org/re/employee/domain/EmployeeRepository.java
core/src/main/java/org/re/employee/service/EmployeeDomainService.java

---
- resolves #
> 직원 수를 count 하는  api 를 추가하였습니다.

[Feature] 직원 통계 api 추가

---

.github/workflows/deploy-dev-docker.yml
application/Dockerfile
application/build.gradle.kts
batch/Dockerfile
batch/build.gradle.kts
consumer/Dockerfile
consumer/build.gradle.kts
hub/Dockerfile
hub/build.gradle.kts

build: add building simple docker image

---

core/src/main/java/org/re/mdtlog/service/MdtEventService.java

fix: 위치 이력 수신시 차량 업데이트 누락 추가

---

hub/src/main/java/org/re/mdtlog/api/MdtCycleLogApi.java
hub/src/main/java/org/re/mdtlog/api/MdtIgnitionApi.java

feat: 라우팅 키 지정 옵션 (부하 테스트용)

---

core/src/main/java/org/re/driving/repository/impl/DrivingHistoryCustomRepositoryImpl.java

[feat] 월별 통계 데이터 수정

---

application/src/main/java/org/re/driving/api/DrivingHistoryApi.java
application/src/main/java/org/re/driving/api/payload/CurrentDrivingInfo.java
application/src/main/java/org/re/driving/service/DrivingHistoryService.java
core/src/main/java/org/re/common/exception/CommonAppExceptionCode.java

feat: 현재 주행 조회 API

---

application/src/main/java/org/re/employee/api/payload/AccountStatus.java
application/src/main/java/org/re/employee/service/EmployeeService.java

feat: AccountStatus enum 수정
